spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://us-cdbr-iron-east-02.cleardb.net/heroku_7b054e039375509?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bb59108c945bd6
    password: 4c3d01af
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:      
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
        

 
server:
  port: 8081
  